# labeler "full" schema

# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    Thank you @{{ issue.user.login }} for suggesting this.
    Please follow the issue templates.
  prs: |
    Thank you for suggesting this.
    Please follow the issue templates.

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  'invalid':
    include:
      - '\Put the copied text here\, by replacing this line\'
    exclude:
      - '\Possible solution for the problem\.\'
      - '\Your Question\(s\) \/ Uw vraag\'
