labels:
  - name: invalid
    labeled:
      issue:
        body: Thank you @{{ issue.user.login }} for suggesting this. Please follow the issue templates.
        action: close
  - name: wontfix
    labeled:
      issue:
        body: This will not be worked on but I appreciate your contribution.
        action: close
    unlabeled:
      issue:
        body: This has become active again.
        action: open
  - name: duplicate
    labeled:
      issue:
        body: This issue already exists.
        action: close
  - name: unable to reproduce 
    labeled:
      issue:
        body: I can't reproduce your issue. Please give more information (e.g. screenshots)
  - name: in progress
    labeled:
      issue:
        body: It takes longer than expected to solve this issue. I'm working on it. Please be patience
