name: EasyDutch
description: Issue tracker for EasyDutch
body:
  - type: checkboxes
    attributes:
      label: Prerequisites / Vereisten
      description: To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: This is a **Dutch** website, so no general websites with Dutch subdomains (e.g. nl.y8.com) / 
                 Het is een **Nederlandse** website, dus geen websites met Nederlandse subdomeinen (bijv. nl.y8.com)
          required: true
        - label: I performed a cursory search of the issue tracker to avoid opening a duplicate issue / Geen **duplicaten**!!
          required: true
        - label: Only ads or anti-adblock / Alleen advertenties of anti-adblock
          discription: |
            - Privacy stuff should be reported at uBlock Origin or EasyPrivacy / Privacy dingen moet u melden aan uBlock of EasyPrivacy
            - No annoyances 
          required: true
    
  - type: checkboxes
    attributes:
      label: I tried to reproduce the issue when...
      options:
        - label: uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
          required: true
        - label: uBlock Origin is the only extension / uBlock Origin is de enige extensie
          required: true

  - type: textarea
    attributes:
      label: URL(s) where the issue occurs / Websites waar het probleem voorkomt
      description: |
        At least one URL for a web page where the clearly described issue occurs is **mandatory**. 
        The backticks (`) surrounding the URLs are important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.
        Geef de link van de website. Waarschuw met "NSFW" als dat nodig is.
      placeholder: |
        `https://example.nl`
        `https://example.be`
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the issue
      description: |
        Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.
        Wees zo duidelijk mogelijk: niemand kan je gedachten lezen en niemand kijkt over je schouder mee.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Screenshot(s) for **difficult to describe visual issues are mandatory**. 
        Post **links** instead of inline images for screenshots containing **Adult material**.
        Is het **Volwassen materiaal** post dan linkjes in plaats van **Inline Images**.
    validations:
      required: false

  - type: input
    attributes:
      label: uBlock Origin version
    validations:
      required: true

  - type: input
    attributes:
      label: Browser name and version
    validations:
      required: true

  - type: textarea
    attributes:
      label: Settings
      description: | 
        List all the changes you've made to uBO's default settings here
        Maak hier een lijst van alle wijzigingen die u heeft aangebracht in de standaardinstellingen van uBO 
      placeholder: |
        - Change 1
        - Change 2
        - Change 3
    validations:
      required: false  

  - type: textarea
    attributes:
      label: Notes
      description: |
        Please investigate the issues you report -- this prevents burdening other volunteers. 
        This is especially true for issues arising from settings which are very different from default ones.
      placeholder: |
        Write here the result of whatever investigation work you have done
        Schrijf hier het resultaat van het onderzoekswerk dat je hebt gedaan
    validations:
      required: false
