name: Copy EasyDutch as Back-up

on:
  schedule:
    - cron: "00 07 * * 2,4,6"
  workflow_dispatch:

jobs:
  publish:
    name: Clone EasyDutch
    runs-on: ubuntu-latest
    steps:
      - name: Clone EasyDutch as Back-up
        uses: actions/checkout@v3
      - name: Change permissions
        run: chmod +x ./.github/update-back-up.sh
      - name: Fetch EasyDutch
        run: |
          ./.github/update-back-up.sh
      - name: Commit changes, if any
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "BPower0036"
            git config user.email "<>"
            git add -u EasyDutch/
            git commit -m "Updated from @EasyDutch-uBO"
            git push origin main
          fi
