name: Delete old workflow runs
on:
  workflow_dispatch:
  schedule:
    - cron: '00 05 1 * *'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete `Copy EasyDutch as Back-up` workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: Copy EasyDutch as Back-up
          retain_days: 7
          keep_minimum_runs: 4
      - name: Delete `Delete old workflow runs` workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: Delete old workflow runs
          retain_days: 0
          keep_minimum_runs: 1
      - name: Delete `Label Commenter` workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: Label Commenter
          retain_days: 0
          keep_minimum_runs: 2
